# plots for fig s2
library("shape")
library("metacell")

gen_fig_s2_plots = function() {
  
  fig_dir = "figs/paper_figs/fig_s2"
  if(!dir.exists(fig_dir)) {
    dir.create(fig_dir)
  }
  
  # Figure S2A relies on all the data saved in data/parameter_stability_analysis/
  # this data is generated by the function gen_parameter_stability_analysis() in scripts/parameter_stability_analysis.r
  # Regenerating this data takes some time because mgraphs and mctnetwork objects have to be constructed for each sampled parameter value
  
  fig_s2a()
  #fig_s2b()
  
}

fig_s2a = function() {
  
  fig_dir = "figs/paper_figs/fig_s2/fig_s2a"
  
  if(!dir.exists(fig_dir)) {
    dir.create(fig_dir)
  }
  
  plot_cell_type_transition_frequencies()
  
  plot_logist_function_scale_param(fig_dir = fig_dir)
  plot_logist_function_loc_param(fig_dir = fig_dir)
  plot_convex_potential_cap_var_factor(fig_dir = fig_dir)
  plot_convex_potential_off_cap_cost1(fig_dir = fig_dir)
  plot_convex_potential_off_cap_cost2(fig_dir = fig_dir)
  
}



plot_cell_type_transition_frequencies  = function(plot_pdf = T) {
  n_transitions = 30
  cex_dot = 3
  
  param_ls = c("t_exp","logist_loc","logist_scale","max_degree_mc","cap_var_factor","off_capacity_cost1","off_capacity_cost2")
  
  param_nms = c("Markov process time t","Logistic loc","Logistic scale","Maximal degree metacell graph","Allowed capacity variance","Capacity cost 1","Capacity cost 2")
  names(param_nms) = param_ls
  
  load("data/parameter_stability_analysis/ls_of_param.Rda")
  load("data/parameter_stability_analysis/net_id_ls_f.Rda")
  
  fig_dir = "figs/paper_figs/fig_s2"
  if(!dir.exists(fig_dir)) {
    dir.create(fig_dir)
  }
  fig_dir = "figs/paper_figs/fig_s2/fig_s2a"
  if(!dir.exists(fig_dir)) {
    dir.create(fig_dir)
  }
  
  mct = scdb_mctnetwork("sing_emb_wt10")
  mat = scdb_mat("sing_emb_wt10")
  mc_wt = scdb_mc("sing_emb_wt10_recolored")
  
  all_colors = unique(mc_wt@colors)
  
  cls_f = names(mc_wt@mc)
  
  cls_spl = split(cls_f,mat@cell_metadata[cls_f,"age_group"])
  
  col_dist_zero = matrix(0,nrow = ncol(mc_wt@e_gc),ncol = length(all_colors))
  rownames(col_dist_zero) = c(1:ncol(mc_wt@e_gc))
  colnames(col_dist_zero) = all_colors
  
  col_dist_per_t = lapply(cls_spl,function(cls) {
    
    col_dist = col_dist_zero
    col_dist_tmp = table(mc_wt@mc[cls],mc_wt@colors[mc_wt@mc[cls]])
    col_dist_tmp = col_dist_tmp/rowSums(col_dist_tmp)
    
    col_dist[rownames(col_dist_tmp),colnames(col_dist_tmp)] = col_dist_tmp
    
    return(col_dist)
  })
  
  col_trans_per_t = lapply(c(1:length(mct@mc_forward)),function(i) {
    
    mc_trans = mct@mc_t_infer[,i]*mct@mc_forward[[i]]
    
    col_trans = t(col_dist_per_t[[i]]) %*% mc_trans %*% col_dist_per_t[[i+1]]
    return(col_trans)
  })
  
  col_dist_orig_all = col_trans_per_t[[1]]/12
  for(t in 2:12) {
    col_dist_orig_all = col_dist_orig_all + col_trans_per_t[[t]]/12
  }
  
  
  
  
  
  for (param in param_ls) {
    print(param)
    n_param = length(grep(pattern = param,x = net_id_ls_f,v = T))
    
    param_vals = ls_of_param[[param]]
    
    param_nm = param_nms[param]
    
    load(sprintf("data/parameter_stability_analysis/%s_all.Rda",param))
    
    mean_ct_trans_ls = list()
    mean_trans = matrix(0,nrow = 29, ncol = 29)
    
    for (i in 1:length(col_dist_all[[1]])) {
      
      mean_ct_trans = col_dist_all[[1]][[i]]/12
      
      for (t in 2:12) {
        mean_ct_trans = mean_ct_trans + col_dist_all[[t]][[i]]/12
      }
      mean_ct_trans_ls[[i]] = mean_ct_trans
      mean_trans = mean_trans + mean_ct_trans/length(col_dist_all[[1]])
    }
    
    shades = colorRampPalette(RColorBrewer::brewer.pal(9,name = "YlGnBu"))(n_param)
    
    
    # next set diagonal elements zero
    diag(mean_trans) = 0
    
    #top_trans = tail(order(as.vector(col_dist_orig)),n_transitions)
    top_trans = tail(order(as.vector(mean_trans)),n_transitions)
    
    row_ind = as.vector(row(mean_trans))[top_trans]
    col_ind = as.vector(col(mean_trans))[top_trans]
    
    col_dist_param = sapply(mean_ct_trans_ls,function(col_dist) {
      
      col_prob = c()
      
      for (j in 1:n_transitions) {
        col_prob = c(col_prob,col_dist[row_ind[j],col_ind[j]])
      }
      return(col_prob)
    })
    
    orig_trans_val = c()
    for (j in 1:n_transitions) {
      orig_trans_val = c(orig_trans_val,col_dist_orig_all[row_ind[j],col_ind[j]])
    }
    
    y_scale = max(col_dist_param,orig_trans_val)
    
    if(plot_pdf) {
      pdf(sprintf("%s/%s_top_transition_cell_types.pdf",fig_dir,param),w = 9, h = 9/4*3,useDingbats = F)
    } else {
      png(sprintf("%s/%s_top_transition_cell_types.png",fig_dir,param),w = 600, h = 450)
    }
    
    plot(x = c(1:n_transitions),y = orig_trans_val,pch = 21, bg =  "black",cex = cex_dot,col = "black",lwd = 0.5,
         ylim = c(-0.2*y_scale,1.05*y_scale),main = param_nm,ylab = "Frequency",xlab = "")
    abline(h = 0)
    for (j in 1:ncol(col_dist_param)) {
      points(x = c(1:n_transitions),y = col_dist_param[,j],bg = shades[j],cex = cex_dot,pch = 21,col = "black",lwd = 0.5)
    }
    points(x = c(1:n_transitions),y = orig_trans_val,pch = 21, bg =  "red",cex = cex_dot,col = "red",lwd = 0.5)
    points(x = c(1:n_transitions), y = rep(-0.2*y_scale,n_transitions),col = all_colors[row_ind],pch = 19,cex = 3)
    points(x = c(1:n_transitions), y = rep(-0.05*y_scale,n_transitions),col = all_colors[col_ind],pch = 19,cex = 3)
    Arrows(x0 = c(1:n_transitions),x1 = c(1:n_transitions),y0 = rep(-0.2*y_scale,n_transitions),y1 = rep(-0.1*y_scale,n_transitions))
    if(plot_pdf) {
      legend(x = "topleft",pch = 19,legend = sapply(param_vals,function(v) {sprintf("%1.2f",v)}),col = shades,cex = 1.3)
    } else {
      legend(x = "topleft",pch = 19,legend = sapply(param_vals,function(v) {sprintf("%1.2f",v)}),col = shades,cex = 1.3)
    }
    dev.off()
    
    
    
    if(0) {
      mean_bs_dist[[13]] = mean_trans
      
      col_dist_all[[13]] = mean_ct_trans_ls
      
      for (t in 1:13) {
        
        
        
        col_dist_orig = col_trans_per_t[[t]]
        mean_bs_dist_t = mean_bs_dist[[t]]
        
        # next set diagonal elements zero
        diag(mean_bs_)
        
        #top_trans = tail(order(as.vector(col_dist_orig)),n_transitions)
        top_trans = tail(order(as.vector(mean_bs_dist_t)),n_transitions)
        
        row_ind = as.vector(row(col_dist_orig))[top_trans]
        col_ind = as.vector(col(col_dist_orig))[top_trans]
        
        col_dist_bs = sapply(col_dist_all[[t]],function(col_dist) {
          
          col_prob = c()
          
          for (j in 1:n_transitions) {
            col_prob = c(col_prob,col_dist[row_ind[j],col_ind[j]])
          }
          return(col_prob)
        })
        
        col_dist_bs_box = apply(col_dist_bs,1,function(x) return(list(x)))
        col_dist_bs_box = lapply(col_dist_bs_box,function(x) return(x[[1]]))
        
        orig_trans_val = c()
        for (j in 1:n_transitions) {
          orig_trans_val = c(orig_trans_val,col_dist_orig[row_ind[j],col_ind[j]])
        }
        
        col_dist_bs = sqrt(col_dist_bs)
        orig_trans_val = sqrt(orig_trans_val)
        
        y_scale = max(col_dist_bs,orig_trans_val)
        
        png(sprintf("%s/top_transition_t_%d.png",fig_dir,t),w = 800, h = 400)
        plot(x = c(1:n_transitions),y = orig_trans_val,pch = 19, col =  "black",cex = 1.5,
             ylim = c(-0.2*y_scale,1.05*max(col_dist_bs,orig_trans_val)),main = sprintf("Parameter %s age groups %d to %d",param,t,t+1))
        abline(h = 0)
        for (j in 1:ncol(col_dist_bs)) {
          points(x = c(1:n_transitions),y = col_dist_bs[,j],col = shades[j],cex = 1.5,pch = 19)
        }
        points(x = c(1:n_transitions),y = orig_trans_val,pch = 19, col =  "black",cex = 1.5)
        points(x = c(1:n_transitions), y = rep(-0.2*y_scale,n_transitions),col = all_colors[row_ind],pch = 19,cex = 3)
        points(x = c(1:n_transitions), y = rep(-0.05*y_scale,n_transitions),col = all_colors[col_ind],pch = 19,cex = 3)
        Arrows(x0 = c(1:n_transitions),x1 = c(1:n_transitions),y0 = rep(-0.2*y_scale,n_transitions),y1 = rep(-0.1*y_scale,n_transitions))
        
        dev.off()
        
      }
      
    }
    
  }
  
}



plot_logist_function_scale_param = function(fig_dir,plot_pdf = T) {
  
  default_scl = 0.2
  
  param_ls = c(0.10,0.15,0.20,0.25,0.30,0.35,0.45,0.60,0.80)
  scl_ls = param_ls
  scl = scl_ls[1]
  a = plogis(c(0:20)/10,location = 1,scale = scl)
  
  shades = colorRampPalette(RColorBrewer::brewer.pal(n = 9,name = "YlGnBu"))(length(scl_ls))
  
  if(plot_pdf) {
    pdf(sprintf("%s/logistic_function_scale_parameter.pdf",fig_dir),useDingbats = F)
  } else {
    png(sprintf("%s/scale_parameter_logistic_function.png",fig_dir))
  }
  plot(x =c(0:20)/10, y = a,type = "l",lwd = 4,col = shades[1],xlab = "Gene log fold change",ylab = "Cost",main = "Logistic scale")
  
  for (i in 2:length(scl_ls)) {
    scl = scl_ls[i]
    a = plogis(c(0:20)/10,location = 1,scale = scl) - plogis(0,1,scl)
    points(x =c(0:20)/10, y = a,type = "l",lwd = 4,col = shades[i])
  }
  scl = default_scl
  a = plogis(c(0:20)/10,location = 1,scale = scl) - plogis(0,1,scl)
  points(x =c(0:20)/10, y = a,type = "l",lwd = 4,col = "red")
  #legend(x = "topleft",lty = "solid",legend = sapply(scl_ls,function(v) {sprintf("%1.2f",v)}),col = shades,lwd = 4,title = "Scale")
  dev.off()
  
}


plot_logist_function_loc_param = function(fig_dir,plot_pdf = T) {
  
  default_loc = 1
  default_scl = 0.2
  
  param_ls = c(0,0.25,0.5,0.75,1,1.5,2,2.5)
  loc_ls = param_ls
  loc = loc_ls[1]
  a = plogis(c(0:20)/10,location = loc,scale = default_scl)
  
  shades = colorRampPalette(RColorBrewer::brewer.pal(n = 9,name = "YlGnBu"))(length(loc_ls))
  
  if(plot_pdf) {
    pdf(sprintf("%s/logistic_function_loc_parameter.pdf",fig_dir),useDingbats = F)
  } else {
    png(sprintf("%s/logistic_function_loc_parameter.png",fig_dir))
  }
  plot(x =c(0:20)/10, y = a,type = "l",lwd = 4,col = shades[1],xlab = "Gene log fold change",ylab = "Cost",
       main = "Logistic loc",ylim = c(0,1))
  
  for (i in 2:length(loc_ls)) {
    loc = loc_ls[i]
    a = plogis(c(0:20)/10,location = loc,scale = default_scl)
    points(x =c(0:20)/10, y = a,type = "l",lwd = 4,col = shades[i])
  }
  loc = default_loc
  a = plogis(c(0:20)/10,location = loc,scale = default_scl) - plogis(0,loc,default_scl)
  points(x =c(0:20)/10, y = a,type = "l",lwd = 4,col = "red")
  #legend(x = "topleft",lty = "solid",legend = sapply(loc_ls,function(v) {sprintf("%1.2f",v)}),col = shades,lwd = 4,title = "Location")
  dev.off()
  
}

plot_convex_potential_cap_var_factor = function(fig_dir,plot_pdf = T) {
  
  
  param_ls = c(0.01,0.05,0.1,0.25,0.4,0.6,0.8)
  
  default_cap_var_factor = 0.25
  default_off_capacity_cost1 = 1
  default_off_capacity_cost2 = 1000
  
  x_val = seq(-1,1,length.out = 300)
  
  
  y_val = conv_pot(x_val = x_val,cap_var_factor = param_ls[1],off_capacity_cost1 = default_off_capacity_cost1,
                   off_capacity_cost2 = default_off_capacity_cost2)
  
  shades = colorRampPalette(RColorBrewer::brewer.pal(n = 9,name = "YlGnBu"))(length(param_ls))
  
  if(plot_pdf) {
    pdf(sprintf("%s/penalty_function_capacity_variance_factor.pdf",fig_dir),useDingbats = F)
  } else {
    png(sprintf("%s/penalty_function_capacity_variance_factor.pdf",fig_dir))
  }
  plot(x = x_val, y = y_val,type = "l",lwd = 4,col = shades[1],xlab = "Relative difference from expected frequency",
       main = "Allowed capacity variance",ylim = c(0,1000),ylab = "Cost")
  
  for (i in 2:length(param_ls)) {
    
    y_val = conv_pot(x_val = x_val,cap_var_factor = param_ls[i],off_capacity_cost1 = default_off_capacity_cost1,
                     off_capacity_cost2 = default_off_capacity_cost2)
    points(x = x_val, y = y_val,type = "l",lwd = 4,col = shades[i])
  }
  
  y_val  = y_val = conv_pot(x_val = x_val,cap_var_factor = default_cap_var_factor,off_capacity_cost1 = default_off_capacity_cost1,
                            off_capacity_cost2 = default_off_capacity_cost2)
  
  points(x = x_val, y = y_val,type = "l",lwd = 4,col = "red")
  #legend(x = "top",lty = "solid",legend = sapply(param_ls,function(v) {sprintf("%1.2f",v)}),col = shades,lwd = 4,title = "Capacity variance")
  dev.off()  
  
  
  
}


plot_convex_potential_off_cap_cost1 = function(fig_dir,plot_pdf = T) {
  
  
  param_ls = c(0,1,2,5,10,20,50,100)
  
  default_cap_var_factor = 0.25
  default_off_capacity_cost1 = 1
  default_off_capacity_cost2 = 1000
  
  x_val = seq(-1,1,length.out = 300)
  
  
  y_val = conv_pot(x_val = x_val,cap_var_factor = default_cap_var_factor,off_capacity_cost1 = param_ls[1],
                   off_capacity_cost2 = default_off_capacity_cost2)
  
  shades = colorRampPalette(RColorBrewer::brewer.pal(n = 9,name = "YlGnBu"))(length(param_ls))
  
  if(plot_pdf) {
    pdf(sprintf("%s/penalty_function_off_cap_cost1.pdf",fig_dir),useDingbats = F)
  } else {
    png(sprintf("%s/penalty_function_off_cap_cost1.png",fig_dir))
  }
  plot(x = x_val, y = y_val,type = "l",lwd = 4,col = shades[1],xlab = "Relative difference from expected frequency",
       main = "Capacity cost 1",ylim = c(0,25),ylab = "Cost",xlim = c(-0.3,0.3))
  
  for (i in 2:length(param_ls)) {
    
    y_val = conv_pot(x_val = x_val,cap_var_factor = default_cap_var_factor,off_capacity_cost1 = param_ls[i],
                     off_capacity_cost2 = default_off_capacity_cost2)
    points(x = x_val, y = y_val,type = "l",lwd = 4,col = shades[i])
  }
  
  y_val  = y_val = conv_pot(x_val = x_val,cap_var_factor = default_cap_var_factor,off_capacity_cost1 = default_off_capacity_cost1,
                            off_capacity_cost2 = default_off_capacity_cost2)
  
  points(x = x_val, y = y_val,type = "l",lwd = 4,col = "red")
  #legend(x = "top",lty = "solid",legend = sapply(param_ls,function(v) {sprintf("%d",v)}),col = shades,lwd = 4,title = "Capacity cost 1")
  dev.off()  
  
  
  
}

plot_convex_potential_off_cap_cost2 = function(fig_dir,plot_pdf = T) {
  
  
  param_ls = c(1,10,20,50,100,200,500,1000,2000,5000)
  
  default_cap_var_factor = 0.25
  default_off_capacity_cost1 = 1
  default_off_capacity_cost2 = 1000
  
  x_val = seq(-1,1,length.out = 300)
  
  
  y_val = conv_pot(x_val = x_val,cap_var_factor = default_cap_var_factor,off_capacity_cost1 = default_off_capacity_cost1,
                   off_capacity_cost2 = param_ls[1])
  
  shades = colorRampPalette(RColorBrewer::brewer.pal(n = 9,name = "YlGnBu"))(length(param_ls))
  
  if(plot_pdf) {
    pdf(sprintf("%s/penalty_function_off_cap_cost2.pdf",fig_dir),useDingbats = F)
  } else {
    png(sprintf("%s/penalty_function_off_cap_cost2.pdf",fig_dir))
  }
  plot(x = x_val, y = y_val,type = "l",lwd = 4,col = shades[1],xlab = "Relative difference from expected frequency",
       main = "Capacity cost 2",ylim = c(0,1000),ylab = "Cost")
  
  for (i in 2:length(param_ls)) {
    
    y_val = conv_pot(x_val = x_val,cap_var_factor = default_cap_var_factor,off_capacity_cost1 = default_off_capacity_cost1,
                     off_capacity_cost2 = param_ls[i])
    points(x = x_val, y = y_val,type = "l",lwd = 4,col = shades[i])
  }
  
  y_val  = y_val = conv_pot(x_val = x_val,cap_var_factor = default_cap_var_factor,off_capacity_cost1 = default_off_capacity_cost1,
                            off_capacity_cost2 = default_off_capacity_cost2)
  
  points(x = x_val, y = y_val,type = "l",lwd = 4,col = "red")
  #legend(x = "top",lty = "solid",legend = sapply(param_ls,function(v) {sprintf("%d",v)}),col = shades,lwd = 4,title = "Capacity cost 2")
  dev.off()  
  
  
  
}

conv_pot = function(x_val,cap_var_factor = 0.25,off_capacity_cost1 = 1,off_capacity_cost2 = 1000) {
  y_cap = off_capacity_cost1*cap_var_factor
  
  y_val = sapply(x_val,function(x) {
    
    if(x < -cap_var_factor) {
      y = y_cap + (-cap_var_factor - x)*off_capacity_cost2
    } else if (x < 0 ) {
      y = (-x)*off_capacity_cost1
    } else if (x < cap_var_factor) {
      y = x*off_capacity_cost1
    } else {
      y = y_cap + (x - cap_var_factor)*off_capacity_cost2
    }
    
    return(y)
  })
  
  return(y_val)
}



if(0) {
  
  # this figure needs the large amount of replica data generated by the statistical stability analysiss 
  fig_s2b = function(n_transitions = 20,plot_pdf = T) {
    
    
    fig_dir = "figs/paper_figs/fig_s2/fig_s2b/"
    if(!dir.exists(fig_dir)) {
      dir.create(fig_dir)
    }
    
    #color_distributions are saved in col_dist
    load(file = "data/bootstrap/color_transitions/col_dist_all.Rda")
    
    mct = scdb_mctnetwork("sing_emb_wt10")
    mat = scdb_mat("sing_emb_wt10")
    mc_wt = scdb_mc("sing_emb_wt10_recolored")
    
    all_colors = unique(mc_wt@colors)
    
    cls_f = names(mc_wt@mc)
    
    cls_spl = split(cls_f,mat@cell_metadata[cls_f,"age_group"])
    
    col_dist_zero = matrix(0,nrow = ncol(mc_wt@e_gc),ncol = length(all_colors))
    rownames(col_dist_zero) = c(1:ncol(mc_wt@e_gc))
    colnames(col_dist_zero) = all_colors
    
    col_dist_per_t = lapply(cls_spl,function(cls) {
      
      col_dist = col_dist_zero
      col_dist_tmp = table(mc_wt@mc[cls],mc_wt@colors[mc_wt@mc[cls]])
      col_dist_tmp = col_dist_tmp/rowSums(col_dist_tmp)
      
      col_dist[rownames(col_dist_tmp),colnames(col_dist_tmp)] = col_dist_tmp
      
      return(col_dist)
    })
    
    col_trans_per_t = lapply(c(1:length(mct@mc_forward)),function(i) {
      
      mc_trans = mct@mc_t_infer[,i]*mct@mc_forward[[i]]
      
      col_trans = t(col_dist_per_t[[i]]) %*% mc_trans %*% col_dist_per_t[[i+1]]
      return(col_trans)
    })
    
    mean_bs_dist = lapply(col_dist_all,function(dist_ls) {
      
      a = dist_ls[[1]]
      for (i in 2:length(dist_ls)) {
        a = a + dist_ls[[i]]
      }
      a = a/length(dist_ls)
      return(a)
    })
    
    
    mean_ct_trans_ls = list()
    
    mean_trans = matrix(0,nrow = 29, ncol = 29)
    
    for (i in 1:153) {
      
      mean_ct_trans = col_dist_all[[1]][[i]]/12
      
      for (t in 2:12) {
        mean_ct_trans = mean_ct_trans + col_dist_all[[t]][[i]]/12
      }
      mean_ct_trans_ls[[i]] = mean_ct_trans
      mean_trans = mean_trans + mean_ct_trans/153
    }
    
    col_dist_orig_all = col_trans_per_t[[1]]/12
    for(t in 2:12) {
      col_dist_orig_all = col_dist_orig_all + col_trans_per_t[[t]]/12
    }
    col_trans_per_t[[13]] = col_dist_orig_all
    mean_bs_dist[[13]] = mean_trans
    
    col_dist_all[[13]] = mean_ct_trans_ls
    
    
    
    
    
    # next some box plots
    
    
    
    for (t in 1:13) {
      
      
      col_dist_orig = col_trans_per_t[[t]]
      mean_bs_dist_t = mean_bs_dist[[t]]
      
      #top_trans = tail(order(as.vector(col_dist_orig)),n_transitions)
      top_trans = tail(order(as.vector(mean_bs_dist_t)),n_transitions)
      
      row_ind = as.vector(row(col_dist_orig))[top_trans]
      col_ind = as.vector(col(col_dist_orig))[top_trans]
      
      col_dist_bs = sapply(col_dist_all[[t]],function(col_dist) {
        
        col_prob = c()
        
        for (j in 1:n_transitions) {
          col_prob = c(col_prob,col_dist[row_ind[j],col_ind[j]])
        }
        return(col_prob)
      })
      
      col_dist_bs_box = apply(col_dist_bs,1,function(x) return(list(x)))
      col_dist_bs_box = lapply(col_dist_bs_box,function(x) return(x[[1]]))
      
      
      #median_per_transition = sapply(col_dist_bs_box,median)
      #
      #col_dist_bs_box = lapply(col_dist_bs_box,function(v) {
      #  if(median(v) > 0.01) {
      #    return(v/median(v))
      #  } else {
      #    return(v)
      #  }
      #})
      
      
      
      orig_trans_val = c()
      for (j in 1:n_transitions) {
        orig_trans_val = c(orig_trans_val,col_dist_orig[row_ind[j],col_ind[j]])
      }
      
      #f = median_per_transition > 0.01
      #orig_trans_val[f] = orig_trans_val[f]/median_per_transition[f]
      y_scale = max(col_dist_bs,orig_trans_val)
      if(plot_pdf) {T
        pdf(sprintf("%s/top_transition_t_%d.pdf",fig_dir,t),w = 12, h = 6,useDingbats = F)
      } else {
        png(sprintf("%s/top_transition_t_%d.png",fig_dir,t),w = 800, h = 400)
      }
      
      if(t == 13) {
        main_nm = "Average top %d transitions"
      } else {
        main_nm = sprintf("Top %d transitions between t =  %d and t = %d",n_transitions,t,t+1)
      }
      
      boxplot(col_dist_bs_box,ylim = c(-0.2*y_scale,1.05*max(col_dist_bs,orig_trans_val)),main = main_nm)
      abline(h = 0)
      points(x = c(1:n_transitions), y = rep(-0.2*y_scale,n_transitions),col = all_colors[row_ind],pch = 19,cex = 3)
      points(x = c(1:n_transitions), y = rep(-0.05*y_scale,n_transitions),col = all_colors[col_ind],pch = 19,cex = 3)
      Arrows(x0 = c(1:n_transitions),x1 = c(1:n_transitions),y0 = rep(-0.2*y_scale,n_transitions),y1 = rep(-0.1*y_scale,n_transitions))
      points(x = c(1:n_transitions),y = orig_trans_val,pch = 19, col =  "red",cex = 1.5)
      dev.off()
    }
    
    
  }
  
  
}