# fig S4
#source("paper_scripts/fig3_plots.r")

library("metacell")
source("scripts/generate_paper_figures/fig4_plots.r")

gen_fig_s4_plots = function() {
  
  if(!dir.exists("figs/paper_figs/fig_s4")) {
    dir.create("figs/paper_figs/fig_s4")
  }
  
  # Figure S4a is generated by the functions of fig3_plots.r
  fig_s4b()
  fig_s4c()
  fig_s4de()
  fig_s4f()
  fig_s4g()
}

fig_s4b = function() {
  
  
  mct = scdb_mctnetwork("sing_emb_wt10")
  mc = scdb_mc("sing_emb_wt10_recolored")
  confu = mctnetwork_get_flow_mat(mct, -2)
  diag(confu) = 0
  
  mat = scdb_mat("sing_emb_wt10")
  mc_ag = table(mc@mc, mat@cell_metadata[names(mc@mc), "age_group"])
  mc_t = apply(mc_ag,1, function(x) sum((1:13)*x)/sum(x))
  
  genes = c("Otx2","Sox9","Gbx2","Fst")
  
  incl_colors = c("#635547","#DABE99","#9e6762","#65A83E","#647a4f","#354E23")
  
  for(gene in genes) {
    plot_time_gene_mc_flow(confu = confu,mc = mc,mc_t = mc_t,gene = gene,incl_colors = incl_colors,fig_dir = "figs/paper_figs/fig_s4/fig_s4b",max_t = 13,fig_pref = "epiblast",plot_pdf = T)
  }
  
  
}

fig_s4c = function() {
  
  
  mct = scdb_mctnetwork("sing_emb_wt10")
  mc = scdb_mc("sing_emb_wt10_recolored")
  confu = mctnetwork_get_flow_mat(mct, -2)
  diag(confu) = 0
  
  mat = scdb_mat("sing_emb_wt10")
  mc_ag = table(mc@mc, mat@cell_metadata[names(mc@mc), "age_group"])
  mc_t = apply(mc_ag,1, function(x) sum((1:13)*x)/sum(x))
  
  genes = c("Eomes","Foxa2","Mixl1","T")
  
  incl_colors = c("#635547","#DABE99","#9e6762","#65A83E","#647a4f","#354E23")
  
  for(gene in genes) {
    plot_time_gene_mc_flow(confu = confu,mc = mc,mc_t = mc_t,gene = gene,incl_colors = incl_colors,fig_dir = "figs/paper_figs/fig_s4/fig_s4c",max_t = 13,fig_pref = "epiblast",plot_pdf = T)
  }
  
  
}

fig_s4de = function() {
  
  fig_dir = "figs/paper_figs/fig_s4"
  
  endo_cts = c("#0F4A9C","#F397C0","#EF5A9D","#F6BFCB","#7F6874")
  ecto_cts = c("#f7f79e","#647a4f","#354E23","#9e6762")
  meso_cts = c("#FACB12","#1a3f52","#DFCDE4","#408DA1","#8DB5CE","#45d1c5","#53f1fc","#B51D8D","#cc7818","#8870ad",
               "#532C8A","#FBBE92","#c9a997","#C72228","#EF4E22")
  ct_all = list(endo = endo_cts,meso = meso_cts,ecto = ecto_cts)
  
  mc = scdb_mc("sing_emb_wt10_recolored")
  mct = scdb_mctnetwork("sing_emb_wt10")
  mc_ag = mct@mc_t_infer
  mc_mean_age = ((mc_ag/rowSums(mc_ag)) %*% c(1:13))[,1]
  
  legc = log2(mc@e_gc + 1e-5)
  
  col_to_rank = c(1:nrow(mc@color_key))
  names(col_to_rank) = mc@color_key$color
  
  mc_ls = lapply(ct_all,function(cts) {return(which(mc@colors %in% cts))})
  p_0_ls = lapply(mc_ls,function(mcs) {
    p_0 = rep(0,ncol(mc@e_gc))
    p_0[mcs] = mc_ag[mcs,13]
    return(p_0)
  })
  
  prop_ls = lapply(p_0_ls,function(p_0) {
    
    prop = mctnetwork_propogate_from_t(mct = mct,t = 13,mc_p = p_0)
    
    return(prop)
  })
  
  mc_ag_inf = mctnetwork_propogate_from_t(mct = mct,t = 13,mc_p = mc_ag[,13])
  
  mc_commit_ls = lapply(prop_ls,function(prop) {
    mc_commit = rowSums(prop$probs)/rowSums(mc_ag_inf$probs)
    return(mc_commit)
  })
  
  mc_ord = order(1000*col_to_rank[mc@colors] + mc_mean_age)
  
  w = 8
  h = 4
  
  pdf(sprintf("%s/fig_s4d_endoderm_commitment.pdf",fig_dir),width =  w, height = h,useDingbats = F)
  plot(x = 1:ncol(mc@e_gc),y = mc_commit_ls$endo[mc_ord],pch = 19,col = mc@colors[mc_ord],xlab = "Metacells",xaxt = 'n',
       main = "Endoderm commitment",ylab = "")
  dev.off()
  
  pdf(sprintf("%s/fig_s4d_mesoderm_commitment.pdf",fig_dir),width =  w, height  = h,useDingbats = F)
  plot(x = 1:ncol(mc@e_gc),y = mc_commit_ls$meso[mc_ord],pch = 19,col = mc@colors[mc_ord],xlab = "Metacells",xaxt = 'n',
       main = "Mesoderm commitment",ylab = "")
  dev.off()
  
  #pdf(sprintf("%s/ectoderm_commitment.pdf",fig_dir),width =  w, height  = h,useDingbats = F)
  #plot(x = 1:ncol(mc@e_gc),y = mc_commit_ls$ecto[mc_ord],pch = 19,col = mc@colors[mc_ord],xlab = "Metacells",xaxt = 'n',
  #     main = "Ectoderm commitment",ylab = "")
  #dev.off()
  
  pdf(sprintf("%s/fig_s4e_endo_vs_mesoderm_commitment.pdf",fig_dir),useDingbats = F)
  plot(mc_commit_ls$endo,mc_commit_ls$meso,pch = 19, col = mc@colors,cex = 1.5,xlab = c("Endoderm commitment"),ylab = "Mesoderm commitment")
  dev.off()
  
  pdf(sprintf("%s/fig_s4e_Mesp1_vs_Foxa2.pdf",fig_dir),useDingbats = F,w = 4.5,h = 5)
  plot(x = legc["Foxa2",],y = legc["Mesp1",],pch = 19,col = mc@colors,
       xlab = "Foxa2 expression",ylab = "Mesp1 expression",cex = 1.5)
  dev.off()
  
  
  
}

fig_s4f = function() {
  
  included_cell_types = c("#65A83E","#635547","#DABE99","#C594BF","#DFCDE4","#c19f70","#F397C0","#c9a997","#C72228")
  
  mat = scdb_mat("sing_emb_wt10")
  mc = scdb_mc("sing_emb_wt10_recolored")
  col_to_rank = c(1:nrow(mc@color_key))
  names(col_to_rank) = mc@color_key$color
  col_to_ct = mc@color_key$group
  names(col_to_ct) = mc@color_key$color
  
  age_group_time = unique(mat@cell_metadata[names(mc@mc),c("transcriptional_rank","developmental_time","age_group")])
  dev_time = round(tapply(age_group_time$developmental_time,age_group_time$age_group,mean),2)
  
  mct_id = "sing_emb_wt10"
  mct = scdb_mctnetwork(mct_id)
  
  load(file = "data/fig_s4/retention_time_replica.Rda")
  
  # next original retention time
  
  
  type_flows = mctnetwork_get_type_flows(mct,1,13)
  
  in_flows = sapply(type_flows,FUN = function(flow_mat) {
    
    diag(flow_mat) =  0
    in_flow = colSums(flow_mat)
    
    return(in_flow)
  })
  
  in_flows = cbind(rowSums(type_flows[[1]]),in_flows)
  tot_in_flow = rowSums(in_flows)
  
  type_ag = sapply(type_flows,FUN = function(flow_mat) {
    
    return(colSums(flow_mat))
  })
  type_ag = cbind(rowSums(type_flows[[1]]),type_ag)
  type_ag_n = type_ag/tot_in_flow
  
  diff_time = diff(dev_time)
  
  av_ret_time = 0.5*(diff_time[2:length(diff_time)] + diff_time[1:(length(diff_time) - 1)])
  av_ret_time = c(diff_time[1]/2,av_ret_time,diff_time[length(diff_time)]/2)
  
  ret_time_type = (type_ag_n %*% av_ret_time)[,1]
  
  col_ord = order(col_to_rank[names(ret_time_type)])
  ret_time_type = ret_time_type[col_ord]  
  
  
  # boxplot of retention times
  ret_time_type = ret_time_type[included_cell_types]
  
  ret_time_replica = ret_time_replica[,included_cell_types]
  
  ret_time_ls = split(24*ret_time_replica,rep(colnames(ret_time_replica),each = nrow(ret_time_replica)))
  ret_time_ls =  ret_time_ls[included_cell_types]
  #names(ret_time_ls) = col_to_ct[included_cell_types]
  names(ret_time_ls) = c("DEc","Epi","PS","NM","LNM","APS","DE","BP","E1")
  
  pdf(file = "figs/paper_figs/fig_s4/fig_s4f.pdf",useDingbats = F)
  boxplot(ret_time_ls,col = included_cell_types,las = 2,names = names(ret_time_ls),ylab = "Retention time in hours",xlab = "Cell types",w = 8,h = 3,horizontal = F)
  points(x = c(1:9),y= 24*ret_time_type,pch = 19)
  dev.off()
  
}

fig_s4g = function() {
  
  if(!dir.exists("figs/paper_figs/fig_s4")) {
    dir.create("figs/paper_figs/fig_s4")
  }
  if(!dir.exists("figs/paper_figs/fig_s4/fig_s4g")) {
    dir.create("figs/paper_figs/fig_s4/fig_s4g")
  }
  
  mct = scdb_mctnetwork("sing_emb_wt10")
  mc = scdb_mc("sing_emb_wt10_recolored")
  confu = mctnetwork_get_flow_mat(mct, -2)
  diag(confu) = 0
  colnames(confu)[1] = "-1"
  
  mat = scdb_mat("sing_emb_wt10")
  mc_ag = table(mc@mc, mat@cell_metadata[names(mc@mc), "age_group"])
  mc_t = apply(mc_ag,1, function(x) sum((1:13)*x)/sum(x))
  
  
  # blood vs amnion chorion rostral mesoderm
  
  genes = c("T","Snai1","Foxc2","Cyp26a1","Frzb","Sp5","Igf2","Msx1","Smarcd3","Myl7")
  
  incl_colors = c("#DABE99","#C594BF","#FBBE92","#DFCDE4","#cc7818","#8DB5CE","#c9a997","#8870ad","#53f1fc","#1a3f52")
  
  for(gene in genes) {
    print(gene)
    plot_time_gene_mc_flow(confu = confu,mc = mc,mc_t = mc_t,gene = gene,incl_colors = incl_colors,fig_dir = "figs/paper_figs/fig_s4/fig_s4g",max_t = 13,fig_pref = "nascent_mesoderm",plot_pdf = T)
  }
  
  
  
}



if(0) {
  
  # this part needs all the replica mctnetwork objects from the statistical stability analysis of
  # the network flows. 
  
  generate_replica_retention_time_matrix = function() {
    
    scdb_init("scrna_db/",force_reinit = T)
    mat = scdb_mat("sing_emb_wt10")
    mc = scdb_mc("sing_emb_wt10_recolored")
    
    scdb_init("scrna_db/bootstrap/",force_reinit = T)
    
    included_cell_types = c("#65A83E","#635547","#DABE99","#C594BF","#DFCDE4","#c19f70","#F397C0","#c9a997","#C72228")
    
    col_to_rank = c(1:nrow(mc@color_key))
    names(col_to_rank) = mc@color_key$color
    col_to_ct = mc@color_key$group
    names(col_to_ct) = mc@color_key$color
    
    age_group_time = unique(mat@cell_metadata[names(mc@mc),c("transcriptional_rank","developmental_time","age_group")])
    dev_time = round(tapply(age_group_time$developmental_time,age_group_time$age_group,mean),2)
    
    mct_id = "sing_emb_wt10"
    mct = scdb_mctnetwork(mct_id)
    
    ret_time_replica = c()
    
    
    for (i in 1:153) {
      print(i)
      #load(sprintf("data/paper_data/bootstrap/color_transitions/col_trans_per_t_%d.Rda",i))
      
      mct_bs_id = paste0("sing_emb_wt10_",i)
      mct_bs = scdb_mctnetwork(mct_bs_id)
      
      
      type_flows = mctnetwork_get_type_flows(mct_bs,1,13)
      
      in_flows = sapply(type_flows,FUN = function(flow_mat) {
        
        diag(flow_mat) =  0
        in_flow = colSums(flow_mat)
        
        return(in_flow)
      })
      
      in_flows = cbind(rowSums(type_flows[[1]]),in_flows)
      tot_in_flow = rowSums(in_flows)
      
      type_ag = sapply(type_flows,FUN = function(flow_mat) {
        
        return(colSums(flow_mat))
      })
      type_ag = cbind(rowSums(type_flows[[1]]),type_ag)
      type_ag_n = type_ag/tot_in_flow
      
      diff_time = diff(dev_time)
      
      av_ret_time = 0.5*(diff_time[2:length(diff_time)] + diff_time[1:(length(diff_time) - 1)])
      av_ret_time = c(diff_time[1]/2,av_ret_time,diff_time[length(diff_time)]/2)
      
      ret_time_type = (type_ag_n %*% av_ret_time)[,1]
      
      col_ord = order(col_to_rank[names(ret_time_type)])
      ret_time_type = ret_time_type[col_ord]  
      
      ret_time_replica = rbind(ret_time_replica,ret_time_type)
      
    }
    
    save(ret_time_replica,file = "data/fig_s4/retention_time_replica.Rda")
    
    scdb_init("scrna_db/",force_reinit = T)
    
    
  }
  
}
